version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - GOOGLE_SHEET_URL=18fVD_Q13k0CGhh0FZVHqbtfn_S_S5Yt9pyr_IoD2dGo
      - TELEGRAM_TOKEN=5360780324:AAE-9GqiNxALtY7onHYSiIi3dxYLVDNBs9c
      - TELEGRAM_USER_ID=810387306
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
